set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR cortex-m4)

if(WIN32)
    set(GCC_BIN "D:/Arm-None-EABI/bin" CACHE PATH "GNU Arm Embedded bin directory")
    set(_suffix ".exe")
    set(_gcc "${GCC_BIN}/arm-none-eabi-gcc${_suffix}")
    set(_objcopy "${GCC_BIN}/arm-none-eabi-objcopy${_suffix}")
    set(_objdump "${GCC_BIN}/arm-none-eabi-objdump${_suffix}")
    set(_size "${GCC_BIN}/arm-none-eabi-size${_suffix}")
else()
    set(_gcc "arm-none-eabi-gcc")
    set(_objcopy "arm-none-eabi-objcopy")
    set(_objdump "arm-none-eabi-objdump")
    set(_size "arm-none-eabi-size")
endif()

set(CMAKE_C_COMPILER "${_gcc}" CACHE FILEPATH "GCC C compiler")
set(CMAKE_ASM_COMPILER "${_gcc}" CACHE FILEPATH "GCC assembler")
set(CMAKE_LINKER "${_gcc}" CACHE FILEPATH "GCC linker")
set(CMAKE_OBJCOPY "${_objcopy}" CACHE FILEPATH "Image converter")
set(CMAKE_OBJDUMP "${_objdump}" CACHE FILEPATH "Object dumper")
set(CMAKE_SIZE "${_size}" CACHE FILEPATH "Size tool")

set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
